import textwrap


def build_state_code(state_name, blocks):
    lines = []
    lines.append("import hou")
    lines.append("")
    lines.append("from skyforge.forge_states.base_state import BaseState")
    lines.append("from skyforge.forge_states.tool_context import ToolContext")
    lines.append("from skyforge.forge_states.feature_hub import FeatureHub")
    lines.append("from skyforge.forge_states import features as F")
    lines.append("")
    lines.append("")
    lines.append("class State(BaseState):")
    lines.append("    def __init__(self, **kwargs):")
    lines.append("        self.__dict__.update(kwargs)")
    lines.append("        self.scene_viewer = kwargs['scene_viewer']")
    lines.append("        self.state_name = kwargs.get('state_name', '%s')" % state_name)
    lines.append("        super().__init__(scene_viewer=self.scene_viewer, state_name=self.state_name)")
    lines.append("")
    lines.append("        self.ctx = ToolContext(self.scene_viewer, state_name=self.state_name)")
    if blocks:
        for i, b in enumerate(blocks):
            cls_name = b.get("class")
            init_args = b.get("init") or {}
            args_txt = ", ".join(["%s=%r" % (k, v) for k, v in init_args.items()])
            if args_txt:
                lines.append("        self.f{0} = F.{1}({2})".format(i, cls_name, args_txt))
            else:
                lines.append("        self.f{0} = F.{1}()".format(i, cls_name))
            if b.get("hud") is False:
                lines.append("        self.f{0}.hud_enabled = False".format(i))
        feat_list = ", ".join(["self.f{0}".format(i) for i in range(len(blocks))])
        lines.append("        self.hub = FeatureHub([{0}])".format(feat_list))
    else:
        lines.append("        self.hub = FeatureHub([])")
    lines.append("")
    lines.append("    def onEnter(self, kwargs):")
    lines.append("        self.bind_context(self.ctx, kwargs, ensure_geo=True, ensure_mesh=True)")
    if blocks:
        needs_edit_geo = any(b.get("class") in ("HoverMoveFeature", "HoverDrawFeature") for b in blocks)
        if needs_edit_geo:
            lines.append("        self.ctx.ensure_edit_geo()")
        hover_idx = None
        for i, b in enumerate(blocks):
            if b.get("class") == "HoverGadgetFeature":
                hover_idx = i
                break
    if blocks:
        for i, b in enumerate(blocks):
            for setup in b.get("setup") or []:
                method = setup.get("method")
                value = setup.get("value")
                if not method:
                    continue
                lines.append("        self.f{0}.{1}({2})".format(i, method, repr(value)))
        if hover_idx is not None and needs_edit_geo:
            lines.append("        self.f{0}.set_use_edit_geo(True)".format(hover_idx))
    lines.append("        base_template = getattr(self, 'HUD_TEMPLATE', None)")
    lines.append("        if base_template is None:")
    lines.append("            try:")
    lines.append("                has_hud = any(callable(getattr(f, 'hud_template', None)) for f in self.hub.features)")
    lines.append("            except Exception:")
    lines.append("                has_hud = False")
    lines.append("            if has_hud:")
    lines.append("                base_template = {")
    lines.append("                    'title': self.state_name,")
    lines.append("                    'desc': '',")
    lines.append("                    'icon': '$SK_ICONS/devtools.svg',")
    lines.append("                    'rows': [],")
    lines.append("                }")
    lines.append("        self.enter_with_hud(self.hub, self.ctx, kwargs, base_template=base_template, update=True)")
    lines.append("")
    lines.append("    def onExit(self, kwargs):")
    lines.append("        self.hub.exit(self.ctx, kwargs)")
    lines.append("")
    lines.append("    def onMouseEvent(self, kwargs):")
    lines.append("        ui = kwargs.get('ui_event')")
    lines.append("        if ui is None:")
    lines.append("            return False")
    lines.append("        self.ctx.ensure_geo()")
    lines.append("        self.ctx.ensure_mesh(geo=self.ctx.geometry)")
    lines.append("        consumed, payload = self.hub.mouse_collect(self.ctx, kwargs)")
    lines.append("        if payload:")
    lines.append("            self.ctx.set_service('selection_payload', payload)")
    lines.append("            return payload")
    lines.append("        return consumed")
    lines.append("")
    lines.append("    def onDraw(self, kwargs):")
    lines.append("        self.hub.draw(self.ctx, kwargs)")
    lines.append("        self.hub.update_hud(self.scene_viewer, self.ctx)")
    lines.append("")
    lines.append("    def onKeyEvent(self, kwargs):")
    lines.append("        return bool(self.hub.key(self.ctx, kwargs, stop_on_consume=False))")
    lines.append("")
    lines.append("    def onKeyTransitEvent(self, kwargs):")
    lines.append("        try:")
    lines.append("            for f in self.hub._iter_features():")
    lines.append("                method = getattr(f, 'on_key_transit_event', None)")
    lines.append("                if callable(method) and method(self.ctx, kwargs):")
    lines.append("                    return True")
    lines.append("        except Exception:")
    lines.append("            pass")
    lines.append("        return False")
    lines.append("")
    lines.append("    def onMenuAction(self, kwargs):")
    lines.append("        handled = bool(self.hub.menu(self.ctx, kwargs, stop_on_consume=False))")
    lines.append("        if handled:")
    lines.append("            self.hub.update_hud(self.scene_viewer, self.ctx)")
    lines.append("        return handled")
    lines.append("")
    lines.append("    def onMenuPreOpen(self, kwargs):")
    lines.append("        return bool(self.hub.menu_pre_open(self.ctx, kwargs, stop_on_consume=False))")
    lines.append("")
    lines.append("")
    lines.append("def createViewerStateTemplate():")
    lines.append("    state_typename = '%s'" % state_name)
    lines.append("    state_label = '%s'" % state_name)
    lines.append("    state_cat = hou.sopNodeTypeCategory()")
    lines.append("")
    lines.append("    template = hou.ViewerStateTemplate(state_typename, state_label, state_cat)")
    lines.append("    template.bindFactory(State)")
    if blocks:
        feat_classes = ["F.{0}".format(b.get("class")) for b in blocks if b.get("class")]
        if feat_classes:
            lines.append("    feature_classes = [{0}]".format(", ".join(feat_classes)))
            lines.append("    for cls in feature_classes:")
            lines.append("        if hasattr(cls, 'bind_template'):")
            lines.append("            cls.bind_template(template)")
            lines.append("")
            lines.append("    hotkey_defs = hou.PluginHotkeyDefinitions()")
            lines.append("    hotkeys_by_cls = {}")
            lines.append("    for cls in feature_classes:")
            lines.append("        if hasattr(cls, 'build_hotkeys'):")
            lines.append("            hk = cls.build_hotkeys(hotkey_defs, state_typename)")
            lines.append("            if hk:")
            lines.append("                hotkeys_by_cls[cls] = hk")
            lines.append("")
            lines.append("    menu = None")
            lines.append("    for cls in feature_classes:")
            lines.append("        hk = hotkeys_by_cls.get(cls)")
            lines.append("        if menu is None and hasattr(cls, 'build_menu'):")
            lines.append("            menu = cls.build_menu(state_typename, state_label, hotkeys=hk)")
            lines.append("    if menu is not None:")
            lines.append("        for cls in feature_classes:")
            lines.append("            hk = hotkeys_by_cls.get(cls)")
            lines.append("            if hasattr(cls, 'extend_menu'):")
            lines.append("                cls.extend_menu(menu, hotkeys=hk, add_separator=True)")
            lines.append("")
            lines.append("    if menu is not None:")
            lines.append("        template.bindMenu(menu)")
            lines.append("    if hotkeys_by_cls:")
            lines.append("        template.bindHotkeyDefinitions(hotkey_defs)")
    lines.append("    template.bindIcon('$SK_ICONS/devtools.svg')")
    lines.append("    return template")
    lines.append("")
    return textwrap.dedent("\n".join(lines)).strip() + "\n"
